version: '3.8'

services:
  blog:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: jacinli/blog:main
    ports:
      - "56172:80"
    container_name: blog
    restart: unless-stopped
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
    volumes:
      # 可选：挂载日志目录
      - ./logs/nginx:/var/log/nginx
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
